/**
 * Project configuration
 * This file is auto-generated by pipecat-cli
 */

export const AVAILABLE_TRANSPORTS = ['smallwebrtc'];

export const DEFAULT_TRANSPORT = 'smallwebrtc';

export const TRANSPORT_CONFIG = {
  daily: { endpoint: 'http://localhost:7860/start' },
  smallwebrtc: {
    webrtcRequestParams: { endpoint: 'http://localhost:7860/api/offer' },
  },
};

/**
 * Create a transport instance based on the transport type
 * Uses dynamic imports to only load the required transport library
 */
export async function createTransport(transportType) {
  switch (transportType) {
    case 'smallwebrtc': {
      const { SmallWebRTCTransport } = await import(
        '@pipecat-ai/small-webrtc-transport'
      );
      return new SmallWebRTCTransport();
    }

    default:
      throw new Error(`Unsupported transport type: ${transportType}`);
  }
}
