agent_name = "telnyx-chatbot-dial-in"
image = "your_username/telnyx-chatbot-dial-in:0.1"
image_credentials = "your_dockerhub_image_pull_secret"
secret_set = "telnyx-chatbot"
agent_profile = "agent-1x"

[scaling]
	min_agents = 1
