agent_name = "exotel-chatbot-dial-out"
image = "your_username/exotel-chatbot-dial-out:0.1"
image_credentials = "your_dockerhub_image_pull_secret"
secret_set = "exotel-chatbot"

[scaling]
	min_agents = 1
