[project]
name = "code-helper"
version = "0.1.0"
description = "Voice AI bot built with Pipecat"
requires-python = ">=3.10"
dependencies = [
    "pipecat-ai[deepgram,cartesia, elevenlabs,local-smart-turn-v3,openai,runner,silero,webrtc]",
    "pipecat-ai-whisker",
    "pipecat-ai-tail",
]

[dependency-groups]
dev = [
    "pyright>=1.1.404,<2",
    "ruff>=0.12.11,<1",
]

[tool.ruff]
line-length = 100
[tool.ruff.lint]
select = ["I"]

[tool.uv.sources]
pipecat-ai = { path = "../../../pipecat", editable = true }
